name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-ubuntu:
    name: Tests on Ubuntu
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Installation
        run: pnpm install
      - name: Run tests
        run: pnpm run test

  build-windows:
    name: Tests on Windows
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Installation
        run: pnpm install
      - name: Run tests
        run: pnpm run test
